import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: "https://jenniferhaggerty.com/",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 1,
    },
    {
      url: "https://jenniferhaggerty.com/web-development/",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 1,
    },
    {
      url: "https://jenniferhaggerty.com/web-development/portfolio",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://jenniferhaggerty.com/web-development/about",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://jenniferhaggerty.com/web-development/contact",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://jenniferhaggerty.com/photography/",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 1,
      images: [
        "https://jenniferhaggerty.com/images/birds-1.jpg",
        "https://jenniferhaggerty.com/images/birds-2.jpg",
        "https://jenniferhaggerty.com/images/birds-3.jpg",
        "https://jenniferhaggerty.com/images/safara-1.jpg",
        "https://jenniferhaggerty.com/images/sara-2.jpg",
        "https://jenniferhaggerty.com/images/safara-2.jpg",
        "https://jenniferhaggerty.com/images/jennifer-3.jpg",
        "https://jenniferhaggerty.com/images/jennifer-2.jpg",
        "https://jenniferhaggerty.com/images/jennifer-1.jpg",
        "https://jenniferhaggerty.com/images/winter-queen-1.jpg",
        "https://jenniferhaggerty.com/images/winter-queen-2.jpg",
        "https://jenniferhaggerty.com/images/winter-queen-3.jpg",
        "https://jenniferhaggerty.com/images/tiffany-rae-knight-3.jpg",
        "https://jenniferhaggerty.com/images/tiffany-rae-knight-2.jpg",
        "https://jenniferhaggerty.com/images/tiffany-rae-knight-1.jpg",
        "https://jenniferhaggerty.com/images/rozi-1.jpg",
        "https://jenniferhaggerty.com/images/rozi-paige-1.jpg",
        "https://jenniferhaggerty.com/images/paige-1.jpg",
        "https://jenniferhaggerty.com/images/demons-1.jpg",
        "https://jenniferhaggerty.com/images/demons-2.jpg",
        "https://jenniferhaggerty.com/images/demons-3.jpg",
        "https://jenniferhaggerty.com/images/egan-3.jpg",
        "https://jenniferhaggerty.com/images/egan-2.jpg",
        "https://jenniferhaggerty.com/images/egan-1.jpg",
        "https://jenniferhaggerty.com/images/ophelia-1.jpg",
      ],
    },
    {
      url: "https://jenniferhaggerty.com/photography/portfolio",
      lastModified: new Date(),
      changeFrequency: "yearly",
      images: [
        "https://jenniferhaggerty.com/images/birds-1.jpg",
        "https://jenniferhaggerty.com/images/birds-2.jpg",
        "https://jenniferhaggerty.com/images/birds-3.jpg",
        "https://jenniferhaggerty.com/images/safara-1.jpg",
        "https://jenniferhaggerty.com/images/sara-2.jpg",
        "https://jenniferhaggerty.com/images/safara-2.jpg",
        "https://jenniferhaggerty.com/images/jennifer-3.jpg",
        "https://jenniferhaggerty.com/images/jennifer-2.jpg",
        "https://jenniferhaggerty.com/images/jennifer-1.jpg",
        "https://jenniferhaggerty.com/images/winter-queen-1.jpg",
        "https://jenniferhaggerty.com/images/winter-queen-2.jpg",
        "https://jenniferhaggerty.com/images/winter-queen-3.jpg",
        "https://jenniferhaggerty.com/images/tiffany-rae-knight-3.jpg",
        "https://jenniferhaggerty.com/images/tiffany-rae-knight-2.jpg",
        "https://jenniferhaggerty.com/images/tiffany-rae-knight-1.jpg",
        "https://jenniferhaggerty.com/images/rozi-1.jpg",
        "https://jenniferhaggerty.com/images/rozi-paige-1.jpg",
        "https://jenniferhaggerty.com/images/paige-1.jpg",
        "https://jenniferhaggerty.com/images/demons-1.jpg",
        "https://jenniferhaggerty.com/images/demons-2.jpg",
        "https://jenniferhaggerty.com/images/demons-3.jpg",
        "https://jenniferhaggerty.com/images/egan-3.jpg",
        "https://jenniferhaggerty.com/images/egan-2.jpg",
        "https://jenniferhaggerty.com/images/egan-1.jpg",
      ],
    },
    {
      url: "https://jenniferhaggerty.com/photography/about",
      lastModified: new Date(),
      changeFrequency: "yearly",
      images: ["https://jenniferhaggerty.com/photography/images/ophelia-1.jpg"],
    },
    {
      url: "https://jenniferhaggerty.com/photography/prices",
      lastModified: "2025-12-18T14:47:22+00:00",
      changeFrequency: "yearly",
      images: [
        "https://jenniferhaggerty.com/images/galleries/atmos/0126/atmos012610.jpg",
        "https://jenniferhaggerty.com/images/safara-1.jpg",
        "https://jenniferhaggerty.com/images/galleries/pirate-party-1125/pirateparty11202559.jpg",
      ],
    },
    {
      url: "https://jenniferhaggerty.com/photography/contact",
      lastModified: new Date(),
      changeFrequency: "yearly",
    },
    {
      url: "https://jenniferhaggerty.com/photography/gallery",
      lastModified: new Date(),
      changeFrequency: "monthly",
    },
  ];
}
